version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: orange_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: orange_db
      MYSQL_USER: orange_user
      MYSQL_PASSWORD: orange_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_orange.sql:/docker-entrypoint-initdb.d/database_orange.sql
    networks:
      - orange_network

  # PHP-FPM Backend
  backend:
    build:
      context: ./ol_laravel
      dockerfile: Dockerfile
    container_name: ol_laravel
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./ol_laravel:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=orange_db
      - DB_USERNAME=orange_user
      - DB_PASSWORD=orange_pass
      - DB_PORT=3306
    depends_on:
      - mysql
    networks:
      - orange_network

  # Nginx Web Server
  nginx:
    image: nginx:1.25-alpine
    container_name: orange_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ol_laravel/public:/var/www/html/public:ro
    depends_on:
      - backend
    networks:
      - orange_network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: orange_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orange_network

volumes:
  mysql_data:
  redis_data:

networks:
  orange_network:
    driver: bridge 