version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ol_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: orange_db
      MYSQL_USER: orange_user
      MYSQL_PASSWORD: orange_pass
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_orange.sql:/docker-entrypoint-initdb.d/database_orange.sql
    networks:
      - orange_network

  # PHP-FPM Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ol_backend
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=orange_db
      - DB_USERNAME=orange_user
      - DB_PASSWORD=orange_pass
      - DB_PORT=3306
    depends_on:
      - mysql
    networks:
      - orange_network

  # Nginx Web Server
  nginx:
    image: nginx:1.25-alpine
    container_name: ol_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - backend
    networks:
      - orange_network

  # Webhook Service (Go)
  webhook:
    build:
      context: ./webhook-service
      dockerfile: Dockerfile
    container_name: ol_webhook
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=orange_db
      - DB_USER=orange_user
      - DB_PASS=orange_pass
      - LARAVEL_API_URL=http://backend:9000
      - LARAVEL_API_KEY=123
      - GIN_MODE=release
    depends_on:
      - mysql
      - backend
    networks:
      - orange_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis (for caching and sessions)
  # redis:
  #   image: redis:7-alpine
  #   container_name: orange_redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - orange_network

volumes:
  mysql_data:
  # redis_data:

networks:
  orange_network:
    driver: bridge 